http:
  routers:
    immich-https:
      rule: Host(`immich.jsemolik.dev`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: immich

  services:
    immich:
      loadBalancer:
        serversTransport: immich-transport
        servers:
          - url: "http://10.1.0.30:30041"

  serversTransports:
    immich-transport:
      forwardingTimeouts:
        dialTimeout: 30s
        responseHeaderTimeout: 3600s
        idleConnTimeout: 3600s