http:
  routers:
    proxmox:
      rule: Host(`pve.jsemolik.dev`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: proxmox

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.1.0.10:8006"
      serversTransport: proxmox-insecure

serversTransports:
  proxmox-insecure:
    insecureSkipVerify: true
